services:
  mainsail:
    build:
      context: ./mainsail
      dockerfile: mainsail.Dockerfile
    ports:
      - 80:80
    networks:
      - mainsail
    restart: always

  moonraker:
    build:
      context: ./moonraker
      dockerfile: moonraker.Dockerfile
    ports:
      - 7125:7125
    networks:
      - mainsail
    volumes:
      - /opt/printer_data:/root/printer_data:z
    security_opt:
      - label=level:s0
    user: 0:0
    restart: always

  klipper:
    build:
      context: ./klipper
      dockerfile: klipper.Dockerfile
    volumes:
      - /opt/printer_data:/root/printer_data:z
    
    devices:
      - ${MCU_1_DEVICE:-}:/dev/mcu1
      - ${MCU_2_DEVICE:-}:/dev/mcu2
      - ${MCU_3_DEVICE:-}:/dev/mcu3
      - ${MCU_4_DEVICE:-}:/dev/mcu4

    security_opt:
      - label=level:s0
    user: 0:0
    restart: always

networks:
  mainsail:
